### ISSUE TITLE
Clear Maintainers for Extensions

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/community#21]
There is a [Sensu Extensions](https://github.com/sensu-extensions/) org that does not have as much community stewerdship as the plugins do. I'd like to get our arms around whether: 

* we default to inviting plugin maintainers to also maintain extensions
* who's best to champion this additional set of repos

**Comment by majormoses** [comment]
Agreed, I have have seen users voice their frustration at this. My 2 cents are we should not by default invite plugin maintainers but should be evaluated on a case by case basis in terms of how often they are contributing, the level of contribution, and comfort levels of current maintainers of the extensions org. I believe it should probably follow the same (or almost identical) pattern I am in the process out outlining for sensu-plugins governance.

So far I have only had interactions with @agoddard on these repos/orgs and it was purely can you migrate this over to us but have not seen any actual review happen. This needs to change either we need to add maintainers that will be more active and responsive or we need the existing maintainers of extensions to step up their game. Having a public repo that people can't really contribute to is not helpful and maddening as a user.

Due to the lack of engagement I would propose myself and @eheydrick to be added simply because we need to get the ball rolling on stuff and we are the most active plugin maintainers.

**Comment by mbbroberg** [comment]
Agreed on the goal. I know @agoddard and team would love to help where they can, but this org needs more community support to stay on its toes. As a stopgap, I've invited those already trusted as plugin maintainers into the extensions org. Before we can do more than that, we need to focus on improving maintainer workflow, which is happening right now. 

@sensu-plugins/owners will still be responsible for checking the repos in the meantime. 

Updates will come on this thread and ideas are very welcome from the community. Much ❤️ to everyone here.

**Comment by mbbroberg** [comment]
🤦‍♂️ Fat finger 👇

**Comment by mbbroberg** [comment]
I'd like to recommend @luisdavim as the first extensions maintainer (which would resolve this issue). If accepted and +1ed, we can document it in the README.md of this repo if accepted and then start the onboard process. cc @majormoses @eheydrick

**Comment by luisdavim** [comment]
As per @majormoses request I've opened https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/37

**Comment by mbbroberg** [comment]
Oh I could have closed this a while ago. So glad to have you @luisdavim 👏 👏 👏 . We welcome further maintainers as well 😄
